version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - wp-network

  wordpress:
    image: wordpress:php8.4-fpm
    container_name: wordpress
    volumes:
      - ./data/html:/var/www/html
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    networks:
      - wp-network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql-conf/:/root/
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
